[package]
name = "processing-shaders"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
publish = false

[workspace]
resolver = "2"

[dependencies]
spirv-std = { version = "=0.10.0-alpha.1" }
processing-core = { path = "../core" }

[patch.crates-io]
glam = { git = "https://github.com/bitshifter/glam-rs", tag = "0.30.8" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_arch, values("spirv"))'] }
