[workspace]
members = [
    "crates/backends/executorch",
    "crates/bindings",
    "crates/core",
    "crates/platform/android",
    "crates/processing",
    "crates/processing/core",
    "crates/processing/shaders",
    "crates/test-utils",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_arch, values("spirv"))'] }

[workspace.dependencies]

[package]
name = "infers"
version.workspace = true
edition.workspace = true

[dependencies]
infers-core = { path = "crates/core" }
processing = { path = "crates/processing" }
infers-backend-executorch = { path = "crates/backends/executorch" }

[target.'cfg(target_os = "android")'.dependencies]
platform-android = { path = "crates/platform/android" }
