[package]
name = "processing"
version.workspace = true
edition.workspace = true

[dependencies]
processing-core = { path = "core" }
infers-core = { path = "../core" }
fast_image_resize = "5"
image = { version = "0.25", default-features = false }
thiserror = "2"

[build-dependencies]
spirv-builder = "=0.10.0-alpha.1"
