[package]
name = "infers-bindings"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description.workspace = true

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
name = "infers_bindings"

[dependencies]
infers-core = { path = "../core" }
infers-gpu = { path = "../gpu", optional = true }
processing = { path = "../processing", default-features = false }
processing-core = { path = "../processing/core" }
infers-backend-executorch = { path = "../backends/executorch", default-features = false }
uniffi = { version = "=0.29.4", features = ["cli"] }
thiserror.workspace = true
parking_lot.workspace = true

[features]
default = ["portable", "xnnpack", "vulkan"]
portable = ["infers-backend-executorch/portable"]
xnnpack = ["infers-backend-executorch/xnnpack"]
vulkan = [
    "infers-backend-executorch/vulkan",
    "processing/vulkan",
    "dep:infers-gpu",
]

[target.'cfg(target_os = "android")'.dependencies]
platform-android = { path = "../platform/android" }

[build-dependencies]
uniffi = { version = "=0.29.4", features = ["build"] }

[dev-dependencies]
uniffi = { version = "=0.29.4", features = ["bindgen-tests"] }
infers-test-utils = { path = "../test-utils" }

[lints]
workspace = true
