[package]
name = "infers-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description.workspace = true

[features]
vulkan = []

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
infers-processing-core = { path = "../infers-processing-core" }
thiserror.workspace = true

[dev-dependencies]
infers-test-utils = { path = "../infers-test-utils", features = ["vulkan"] }
infers-gpu = { path = "../infers-gpu" }
trybuild = "1.0"

[lints]
workspace = true
