[package]
name = "infers-backend-executorch"
version.workspace = true
edition.workspace = true

[dependencies]
infers-core = { path = "../../core" }
thiserror = "2"
executorch = { version = "0.12.0", features = ["std", "module", "data-loader", "ndarray", "half"] }

[dev-dependencies]
processing = { path = "../../processing" }
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
