[package]
name = "processing-gpu"
version.workspace = true
edition.workspace = true

[dependencies]
processing-core = { path = "../core" }
infers-core = { path = "../../core" }
infers-gpu = { path = "../../gpu" }
ash = "0.38"
thiserror = "2"

[build-dependencies]
spirv-builder = "=0.10.0-alpha.1"

[lints]
workspace = true
