[package]
name = "infers-core"
version.workspace = true
edition.workspace = true

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
processing-core = { path = "../processing/core" }
thiserror.workspace = true

[dev-dependencies]
infers-test-utils = { path = "../test-utils" }

[lints]
workspace = true
