[package]
name = "platform-android"
version.workspace = true
edition.workspace = true

[dependencies]
infers-core = { path = "../../core" }
processing-core = { path = "../../processing/core" }
thiserror = "2"

[dev-dependencies]
processing = { path = "../../processing" }
infers-test-utils = { path = "../../test-utils" }
