[package]
name = "platform-android"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description.workspace = true

[target.'cfg(target_os = "android")'.dependencies]
infers-core = { path = "../../core" }
infers-gpu = { path = "../../gpu" }
ash = "0.38"
thiserror.workspace = true

[target.'cfg(target_os = "android")'.dev-dependencies]
processing = { path = "../../processing" }
infers-gpu = { path = "../../gpu" }

[lints]
workspace = true
