name: Build project

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:

permissions:
  contents: read

concurrency:
  group: kotlin-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/x-build.yml
    permissions:
      contents: read
      actions: write
    secrets: inherit
