name: Continuous integration

on:
  push:
    branches:
      - "master"
    tags-ignore:
      - "v*"
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/x-build.yml
    permissions:
      contents: read
      actions: write
    secrets: inherit
