name: Release

on:
  push:
    tags:
      - "v*"

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    uses: ./.github/workflows/x-build.yml
    with:
      publish: true
      release: true
    permissions:
      contents: read
      packages: write
      actions: write
    secrets: inherit
