name: Publish snapshot

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: snapshot-${{ github.ref }}
  cancel-in-progress: false

jobs:
  snapshot:
    uses: ./.github/workflows/x-build.yml
    with:
      publish: true
      release: false
    permissions:
      contents: read
      packages: write
      actions: write
    secrets: inherit
