name: Build ExecuTorch

on:
  workflow_call:

permissions:
  contents: read

concurrency:
  group: build-executorch-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ExecuTorch (${{ matrix.target }})
    permissions:
      contents: read
      actions: write
    strategy:
      fail-fast: false
      matrix:
        target: [ x86_64-unknown-linux-gnu, android-arm64 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build ExecuTorch
        id: build
        uses: ./.github/actions/build-executorch
        with:
          target: ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.artifact }}
          path: target/executorch
          if-no-files-found: error
          retention-days: 7
